Homework
guardspb/homework pull request #1
Opened 2021-11-10 21:22 UTC by guardspb

I did homework and everything works good.

2021-11-13 21:26 UTC, nikitosboroda requested changes

2021-11-13 21:26 UTC, nikitosboroda commented on homework1/task05.py
> +    for j in range(min(k, n)):
if k > n - should be an error

2021-11-13 21:26 UTC, nikitosboroda commented on homework1/task05.py
> +def find_maximal_subarray_sum(nums: List[int], k: int) -> int:
what will be if k<0?

2021-11-13 21:26 UTC, nikitosboroda commented on homework1/task02.py
> +def check_fibonacci(data: Sequence[int]) -> bool:
1) there could be much easier algorithm
2) let it be the fibb seq only when length of seq >=3

2021-11-13 21:26 UTC, nikitosboroda commented on tests/homework1/test_task02.py
> +    assert check_fibonacci(data) is True
u dont need ```is True``` there

2021-11-13 21:26 UTC, nikitosboroda commented on tests/homework1/test_task02.py
> +def test_positive_cases_tuples(data):
what's the difference with previous tests? list\tuple - doesnt matter

2021-11-13 21:26 UTC, nikitosboroda commented on tests/homework1/test_task02.py
> +    assert check_fibonacci(data) is False
the same about ```is```

2021-11-13 22:13 UTC, guardspb commented
Good evening, dear mentor! I have corrected all tasks according to your remarks.

2021-11-16 18:53 UTC, guardspb commented
Good evening, dear mentor! I sent you the pull request.

2021-11-16 19:26 UTC, nikitosboroda requested changes

2021-11-16 19:26 UTC, nikitosboroda commented on .github/workflows/main.yml
> +          flake8 --max-line-length=120 .
set max 88.. if your row bigger than 88 symbls, so split it

2021-11-16 19:26 UTC, nikitosboroda commented on homework1/task02.py
> +def check_fibonacci(data: Sequence[int]) -> bool:
what will be if ```data = [1, 10]``` or ```data = [1]```?

2021-11-16 19:26 UTC, nikitosboroda commented on homework1/task05.py
> +        return 0
ur func returns integer.. so user couldnt understand that he got ```0``` cause some problems with ```nums``` or ```k```.. he could think 0 - is the max sum

2021-11-16 19:26 UTC, nikitosboroda commented on tests/homework1/test_task05.py
> +
what about negative cases?

2021-11-17 11:21 UTC, guardspb commented
Good evening, dear mentor! I have corrected all tasks according to your remarks.

2021-11-24 20:54 UTC, nikitosboroda approved these changes

2021-11-24 21:28 UTC, merged